// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quain.Repository;

//#nullable disable

namespace Quain.Repository.Migrations
{
    [DbContext(typeof(QuainRadioContext))]
    [Migration("20230923202616_cambio null")]
    partial class cambionull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quain.Domain.Models.Client", b =>
                {
                    b.Property<string>("COD_CLIENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NOM_COM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TIPO_DOC")
                        .HasColumnType("smallint");

                    b.ToTable((string)null);

                    b.ToFunction("FN_GetClientByCodClientCuitName");
                });

            modelBuilder.Entity("Quain.Domain.Models.ClientClassified", b =>
                {
                    b.Property<string>("COD_CLIENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESCRIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puntos_Adic")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PUNTOS (Adic.)");

                    b.Property<string>("RAZON_SOCI")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToFunction("FN_GetClientsClassified");
                });

            modelBuilder.Entity("Quain.Domain.Models.Sale", b =>
                {
                    b.Property<int>("Importe")
                        .HasColumnType("int");

                    b.Property<string>("N_COMP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToFunction("FN_GetBillAmountByNComp");
                });
#pragma warning restore 612, 618
        }
    }
}
